services:
  postgres-db:
    image: postgres:17
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=msa-project
      - POSTGRES_USER=msa-project
      - POSTGRES_PASSWORD=msa-project
    volumes:
      - postgres_data:/var/lib/postgresql/data

  eureka-server:
    build: ./eureka
    ports:
      - "8761:8761"
    environment:
      - EUREKA_HOSTNAME=eureka-server

  gateway-server:
    build: ./gateway
    ports:
      - "8090:8090"

  product-server:
    build: ./product
    ports:
      - "19050:19050"

  order-server:
    build: ./order
    ports:
      - "19010:19010"

volumes:
  postgres_data: