server:
  port: 8090

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: order-server
              uri: lb://order-server
              predicates:
                - Path=/api/v1/orders/**

            - id: product-server
              uri: lb://product-server
              predicates:
                - Path=/api/v1/products/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/