management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus,loggers"
  
  endpoint:
    health:
      show-details: always
      show-components: always
    
    loggers:
      access: read-only

  metrics:
    tags:
      application: ${spring.application.name}

  info:
    env:
      enabled: true

  prometheus:
    metrics:
      export:
        enabled: true
